
// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!


using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;

namespace ResoniteLink
{
    
        public class Field_float : Field
        {
            [JsonPropertyName("value")]
            public float Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_float), "float")]
        public partial class Member { }

        
        public class Field_double : Field
        {
            [JsonPropertyName("value")]
            public double Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_double), "double")]
        public partial class Member { }

        
        public class Field_decimal : Field
        {
            [JsonPropertyName("value")]
            public decimal Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_decimal), "decimal")]
        public partial class Member { }

        
        public class Field_byte : Field
        {
            [JsonPropertyName("value")]
            public byte Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_byte), "byte")]
        public partial class Member { }

        
        public class Field_ushort : Field
        {
            [JsonPropertyName("value")]
            public ushort Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_ushort), "ushort")]
        public partial class Member { }

        
        public class Field_uint : Field
        {
            [JsonPropertyName("value")]
            public uint Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_uint), "uint")]
        public partial class Member { }

        
        public class Field_ulong : Field
        {
            [JsonPropertyName("value")]
            public ulong Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_ulong), "ulong")]
        public partial class Member { }

        
        public class Field_sbyte : Field
        {
            [JsonPropertyName("value")]
            public sbyte Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_sbyte), "sbyte")]
        public partial class Member { }

        
        public class Field_short : Field
        {
            [JsonPropertyName("value")]
            public short Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_short), "short")]
        public partial class Member { }

        
        public class Field_int : Field
        {
            [JsonPropertyName("value")]
            public int Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_int), "int")]
        public partial class Member { }

        
        public class Field_long : Field
        {
            [JsonPropertyName("value")]
            public long Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_long), "long")]
        public partial class Member { }

        
        public class Field_bool : Field
        {
            [JsonPropertyName("value")]
            public bool Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_bool), "bool")]
        public partial class Member { }

        
        public class Field_char : Field
        {
            [JsonPropertyName("value")]
            public char Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_char), "char")]
        public partial class Member { }

        
        public class Field_string : Field
        {
            [JsonPropertyName("value")]
            public string Value { get; set; }
        }

        [JsonDerivedType(typeof(Field_string), "string")]
        public partial class Member { }

        }
