
// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!


using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;

namespace ResoniteLink
{
    
        public class Field_floatQ : Field
        {
                            [JsonPropertyName("x")]
                public float x { get; set; }
                                [JsonPropertyName("y")]
                public float y { get; set; }
                                [JsonPropertyName("z")]
                public float z { get; set; }
                                [JsonPropertyName("w")]
                public float w { get; set; }
                        }

        [JsonDerivedType(typeof(Field_floatQ), "floatQ")]
        public partial class Member { }

        
        public class Field_doubleQ : Field
        {
                            [JsonPropertyName("x")]
                public double x { get; set; }
                                [JsonPropertyName("y")]
                public double y { get; set; }
                                [JsonPropertyName("z")]
                public double z { get; set; }
                                [JsonPropertyName("w")]
                public double w { get; set; }
                        }

        [JsonDerivedType(typeof(Field_doubleQ), "doubleQ")]
        public partial class Member { }

        }
