
// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!


using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;

namespace ResoniteLink
{

    public class Field_float2 : Field
    {
        [JsonPropertyName("x")]
        public float x { get; set; }
        [JsonPropertyName("y")]
        public float y { get; set; }
    }

    [JsonDerivedType(typeof(Field_float2), "float2")]
    public partial class Member { }


    public class Field_float3 : Field
    {
        [JsonPropertyName("x")]
        public float x { get; set; }
        [JsonPropertyName("y")]
        public float y { get; set; }
        [JsonPropertyName("z")]
        public float z { get; set; }
    }

    [JsonDerivedType(typeof(Field_float3), "float3")]
    public partial class Member { }


    public class Field_float4 : Field
    {
        [JsonPropertyName("x")]
        public float x { get; set; }
        [JsonPropertyName("y")]
        public float y { get; set; }
        [JsonPropertyName("z")]
        public float z { get; set; }
        [JsonPropertyName("w")]
        public float w { get; set; }
    }

    [JsonDerivedType(typeof(Field_float4), "float4")]
    public partial class Member { }


    public class Field_double2 : Field
    {
        [JsonPropertyName("x")]
        public double x { get; set; }
        [JsonPropertyName("y")]
        public double y { get; set; }
    }

    [JsonDerivedType(typeof(Field_double2), "double2")]
    public partial class Member { }


    public class Field_double3 : Field
    {
        [JsonPropertyName("x")]
        public double x { get; set; }
        [JsonPropertyName("y")]
        public double y { get; set; }
        [JsonPropertyName("z")]
        public double z { get; set; }
    }

    [JsonDerivedType(typeof(Field_double3), "double3")]
    public partial class Member { }


    public class Field_double4 : Field
    {
        [JsonPropertyName("x")]
        public double x { get; set; }
        [JsonPropertyName("y")]
        public double y { get; set; }
        [JsonPropertyName("z")]
        public double z { get; set; }
        [JsonPropertyName("w")]
        public double w { get; set; }
    }

    [JsonDerivedType(typeof(Field_double4), "double4")]
    public partial class Member { }


    public class Field_byte2 : Field
    {
        [JsonPropertyName("x")]
        public byte x { get; set; }
        [JsonPropertyName("y")]
        public byte y { get; set; }
    }

    [JsonDerivedType(typeof(Field_byte2), "byte2")]
    public partial class Member { }


    public class Field_byte3 : Field
    {
        [JsonPropertyName("x")]
        public byte x { get; set; }
        [JsonPropertyName("y")]
        public byte y { get; set; }
        [JsonPropertyName("z")]
        public byte z { get; set; }
    }

    [JsonDerivedType(typeof(Field_byte3), "byte3")]
    public partial class Member { }


    public class Field_byte4 : Field
    {
        [JsonPropertyName("x")]
        public byte x { get; set; }
        [JsonPropertyName("y")]
        public byte y { get; set; }
        [JsonPropertyName("z")]
        public byte z { get; set; }
        [JsonPropertyName("w")]
        public byte w { get; set; }
    }

    [JsonDerivedType(typeof(Field_byte4), "byte4")]
    public partial class Member { }


    public class Field_ushort2 : Field
    {
        [JsonPropertyName("x")]
        public ushort x { get; set; }
        [JsonPropertyName("y")]
        public ushort y { get; set; }
    }

    [JsonDerivedType(typeof(Field_ushort2), "ushort2")]
    public partial class Member { }


    public class Field_ushort3 : Field
    {
        [JsonPropertyName("x")]
        public ushort x { get; set; }
        [JsonPropertyName("y")]
        public ushort y { get; set; }
        [JsonPropertyName("z")]
        public ushort z { get; set; }
    }

    [JsonDerivedType(typeof(Field_ushort3), "ushort3")]
    public partial class Member { }


    public class Field_ushort4 : Field
    {
        [JsonPropertyName("x")]
        public ushort x { get; set; }
        [JsonPropertyName("y")]
        public ushort y { get; set; }
        [JsonPropertyName("z")]
        public ushort z { get; set; }
        [JsonPropertyName("w")]
        public ushort w { get; set; }
    }

    [JsonDerivedType(typeof(Field_ushort4), "ushort4")]
    public partial class Member { }


    public class Field_uint2 : Field
    {
        [JsonPropertyName("x")]
        public uint x { get; set; }
        [JsonPropertyName("y")]
        public uint y { get; set; }
    }

    [JsonDerivedType(typeof(Field_uint2), "uint2")]
    public partial class Member { }


    public class Field_uint3 : Field
    {
        [JsonPropertyName("x")]
        public uint x { get; set; }
        [JsonPropertyName("y")]
        public uint y { get; set; }
        [JsonPropertyName("z")]
        public uint z { get; set; }
    }

    [JsonDerivedType(typeof(Field_uint3), "uint3")]
    public partial class Member { }


    public class Field_uint4 : Field
    {
        [JsonPropertyName("x")]
        public uint x { get; set; }
        [JsonPropertyName("y")]
        public uint y { get; set; }
        [JsonPropertyName("z")]
        public uint z { get; set; }
        [JsonPropertyName("w")]
        public uint w { get; set; }
    }

    [JsonDerivedType(typeof(Field_uint4), "uint4")]
    public partial class Member { }


    public class Field_ulong2 : Field
    {
        [JsonPropertyName("x")]
        public ulong x { get; set; }
        [JsonPropertyName("y")]
        public ulong y { get; set; }
    }

    [JsonDerivedType(typeof(Field_ulong2), "ulong2")]
    public partial class Member { }


    public class Field_ulong3 : Field
    {
        [JsonPropertyName("x")]
        public ulong x { get; set; }
        [JsonPropertyName("y")]
        public ulong y { get; set; }
        [JsonPropertyName("z")]
        public ulong z { get; set; }
    }

    [JsonDerivedType(typeof(Field_ulong3), "ulong3")]
    public partial class Member { }


    public class Field_ulong4 : Field
    {
        [JsonPropertyName("x")]
        public ulong x { get; set; }
        [JsonPropertyName("y")]
        public ulong y { get; set; }
        [JsonPropertyName("z")]
        public ulong z { get; set; }
        [JsonPropertyName("w")]
        public ulong w { get; set; }
    }

    [JsonDerivedType(typeof(Field_ulong4), "ulong4")]
    public partial class Member { }


    public class Field_sbyte2 : Field
    {
        [JsonPropertyName("x")]
        public sbyte x { get; set; }
        [JsonPropertyName("y")]
        public sbyte y { get; set; }
    }

    [JsonDerivedType(typeof(Field_sbyte2), "sbyte2")]
    public partial class Member { }


    public class Field_sbyte3 : Field
    {
        [JsonPropertyName("x")]
        public sbyte x { get; set; }
        [JsonPropertyName("y")]
        public sbyte y { get; set; }
        [JsonPropertyName("z")]
        public sbyte z { get; set; }
    }

    [JsonDerivedType(typeof(Field_sbyte3), "sbyte3")]
    public partial class Member { }


    public class Field_sbyte4 : Field
    {
        [JsonPropertyName("x")]
        public sbyte x { get; set; }
        [JsonPropertyName("y")]
        public sbyte y { get; set; }
        [JsonPropertyName("z")]
        public sbyte z { get; set; }
        [JsonPropertyName("w")]
        public sbyte w { get; set; }
    }

    [JsonDerivedType(typeof(Field_sbyte4), "sbyte4")]
    public partial class Member { }


    public class Field_short2 : Field
    {
        [JsonPropertyName("x")]
        public short x { get; set; }
        [JsonPropertyName("y")]
        public short y { get; set; }
    }

    [JsonDerivedType(typeof(Field_short2), "short2")]
    public partial class Member { }


    public class Field_short3 : Field
    {
        [JsonPropertyName("x")]
        public short x { get; set; }
        [JsonPropertyName("y")]
        public short y { get; set; }
        [JsonPropertyName("z")]
        public short z { get; set; }
    }

    [JsonDerivedType(typeof(Field_short3), "short3")]
    public partial class Member { }


    public class Field_short4 : Field
    {
        [JsonPropertyName("x")]
        public short x { get; set; }
        [JsonPropertyName("y")]
        public short y { get; set; }
        [JsonPropertyName("z")]
        public short z { get; set; }
        [JsonPropertyName("w")]
        public short w { get; set; }
    }

    [JsonDerivedType(typeof(Field_short4), "short4")]
    public partial class Member { }


    public class Field_int2 : Field
    {
        [JsonPropertyName("x")]
        public int x { get; set; }
        [JsonPropertyName("y")]
        public int y { get; set; }
    }

    [JsonDerivedType(typeof(Field_int2), "int2")]
    public partial class Member { }


    public class Field_int3 : Field
    {
        [JsonPropertyName("x")]
        public int x { get; set; }
        [JsonPropertyName("y")]
        public int y { get; set; }
        [JsonPropertyName("z")]
        public int z { get; set; }
    }

    [JsonDerivedType(typeof(Field_int3), "int3")]
    public partial class Member { }


    public class Field_int4 : Field
    {
        [JsonPropertyName("x")]
        public int x { get; set; }
        [JsonPropertyName("y")]
        public int y { get; set; }
        [JsonPropertyName("z")]
        public int z { get; set; }
        [JsonPropertyName("w")]
        public int w { get; set; }
    }

    [JsonDerivedType(typeof(Field_int4), "int4")]
    public partial class Member { }


    public class Field_long2 : Field
    {
        [JsonPropertyName("x")]
        public long x { get; set; }
        [JsonPropertyName("y")]
        public long y { get; set; }
    }

    [JsonDerivedType(typeof(Field_long2), "long2")]
    public partial class Member { }


    public class Field_long3 : Field
    {
        [JsonPropertyName("x")]
        public long x { get; set; }
        [JsonPropertyName("y")]
        public long y { get; set; }
        [JsonPropertyName("z")]
        public long z { get; set; }
    }

    [JsonDerivedType(typeof(Field_long3), "long3")]
    public partial class Member { }


    public class Field_long4 : Field
    {
        [JsonPropertyName("x")]
        public long x { get; set; }
        [JsonPropertyName("y")]
        public long y { get; set; }
        [JsonPropertyName("z")]
        public long z { get; set; }
        [JsonPropertyName("w")]
        public long w { get; set; }
    }

    [JsonDerivedType(typeof(Field_long4), "long4")]
    public partial class Member { }


    public class Field_bool2 : Field
    {
        [JsonPropertyName("x")]
        public bool x { get; set; }
        [JsonPropertyName("y")]
        public bool y { get; set; }
    }

    [JsonDerivedType(typeof(Field_bool2), "bool2")]
    public partial class Member { }


    public class Field_bool3 : Field
    {
        [JsonPropertyName("x")]
        public bool x { get; set; }
        [JsonPropertyName("y")]
        public bool y { get; set; }
        [JsonPropertyName("z")]
        public bool z { get; set; }
    }

    [JsonDerivedType(typeof(Field_bool3), "bool3")]
    public partial class Member { }


    public class Field_bool4 : Field
    {
        [JsonPropertyName("x")]
        public bool x { get; set; }
        [JsonPropertyName("y")]
        public bool y { get; set; }
        [JsonPropertyName("z")]
        public bool z { get; set; }
        [JsonPropertyName("w")]
        public bool w { get; set; }
    }

    [JsonDerivedType(typeof(Field_bool4), "bool4")]
    public partial class Member { }

}
