name: 'Publish ResoniteLink'
author: 'Jae'
description: 'Builds and publishes a NuGet package for ResoniteLink'

inputs:
  dotnet-version:
    description: 'Version of dotnet to use'
    default: '10.0.x'
    required: false
  additional-args:
    description: 'Additional args to pass to build'
    required: false
    default: ''
  out-folder:
    description: 'Folder to output nugets in'
    required: false
    default: 'nupkgs'
  nuget-token:
    description: 'Token to push to NuGet'
    required: true
  nuget-url:
    description: 'URL to the NuGet repository'
    required: false
    default: 'https://api.nuget.org/v3/index.json'

runs:
  using: composite
  steps:
    - name: 'Build ResoniteLink libraries'
      uses: ./.github/actions/build-link
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        additional-args: ${{ inputs.additional-args }}
        out-folder: ${{ inputs.out-folder }}

    - name: 'Push builds to NuGet'
      shell: bash
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ inputs.nuget-token }} -s ${{ inputs.nuget-url }}
